Fixed link
disgoorg/disgo pull request #156
Opened 2022-05-20 01:59 UTC by BrandonDoesDev

Just fixed a broken link on readme

Don't worry, I'll contribute to the actual code soon ;)

2022-05-20 02:09 UTC, ftqo commented
I believe a set of parentheses need to be removed at the end of the link.

2022-05-20 06:37 UTC, TopiSenpai requested changes
Nice catch

2022-05-20 06:37 UTC, TopiSenpai commented on README.md
> +This example can also be found [here](https://github.com/disgoorg/disgo/blob/development/_examples/ping_pong/example.go())
```suggestion
This example can also be found [here](https://github.com/disgoorg/disgo/blob/development/_examples/ping_pong/example.go)
```

2022-05-21 12:44 UTC, TopiSenpai commented
if you want this merged you should apply my suggestion btw

2022-05-24 08:21 UTC, TopiSenpai approved these changes

2022-05-24 08:21 UTC, merged