payload type consistency fixes
disgoorg/disgo pull request #198
Opened 2022-08-31 22:21 UTC by caneleex

this PR fixes types of some payload fields to match the behavior of the Discord API.

2022-09-04 14:35 UTC, TopiSenpai requested changes

2022-09-04 14:35 UTC, TopiSenpai commented on discord/thread.go
> +	AutoArchiveDuration *AutoArchiveDuration `json:"auto_archive_duration,omitempty"`
`0` gets omitted

2022-09-04 14:35 UTC, TopiSenpai commented on discord/thread.go
> +	AutoArchiveDuration *AutoArchiveDuration `json:"auto_archive_duration,omitempty"`
`0` gets omitted

2022-09-04 14:35 UTC, TopiSenpai commented on discord/thread.go
> +	RateLimitPerUser    *int                 `json:"rate_limit_per_user,omitempty"`
`0` is the default value

2022-09-04 14:35 UTC, TopiSenpai commented on discord/thread.go
> +	RateLimitPerUser    *int                 `json:"rate_limit_per_user,omitempty"`
`0` is the default value

2022-09-04 14:35 UTC, TopiSenpai commented on discord/thread.go
> +	AutoArchiveDuration *AutoArchiveDuration `json:"auto_archive_duration,omitempty"`
`0` gets omitted

2022-09-04 14:35 UTC, TopiSenpai commented on discord/thread.go
> +	AutoArchiveDuration *AutoArchiveDuration `json:"auto_archive_duration,omitempty"`
`0` gets omitted

2022-09-04 14:35 UTC, TopiSenpai commented on discord/thread.go
> +	AutoArchiveDuration *AutoArchiveDuration `json:"auto_archive_duration,omitempty"`
`0` gets omitted

2022-09-04 14:35 UTC, TopiSenpai commented on discord/thread.go
> +	Invitable           *bool                `json:"invitable"`
does this default to false? we should check

2022-09-04 14:35 UTC, TopiSenpai commented on discord/user.go
> +	Username *string              `json:"username,omitempty"`
username can't be empty so this does not need to be a pointer

2022-09-04 14:35 UTC, TopiSenpai commented on discord/voice_state.go
> +	UserVoiceStateUpdate
can we just paste the 2 fields? as making a struct like this is kinda annoying

2022-09-04 14:35 UTC, TopiSenpai commented on discord/voice_state.go
> +	ChannelID *json.Nullable[snowflake.ID] `json:"channel_id,omitempty"`
`0` should kick the user out of a channel

2022-09-04 15:57 UTC, caneleex commented on discord/role.go
> +	Position *json.Nullable[int] `json:"position,omitempty"`
it is optional. it just resets the position and moves the role all the way to the bottom.

2022-09-04 16:01 UTC, TopiSenpai commented on discord/role.go
> +	Position *json.Nullable[int] `json:"position,omitempty"`
the bottom would be the same as 0 I guess?

2022-09-07 09:04 UTC, TopiSenpai requested changes
some minor stuff I noticed

2022-09-07 09:04 UTC, TopiSenpai commented on discord/guild_scheduled_event.go
> +	EntityMetaData     *json.Nullable[EntityMetaData] `json:"entity_metadata,omitempty"`
I don't think this needs to be a `json.Nullable[T]` as the fields inside are the important part here. You can reset the fields inside by making them empty

2022-09-07 12:40 UTC, TopiSenpai approved these changes

2022-09-07 12:54 UTC, merged