add role connections
disgoorg/disgo pull request #219
Opened 2022-12-08 14:52 UTC by caneleex

https://github.com/discord/discord-api-docs/pull/5668

2022-12-13 00:12 UTC, TopiSenpai requested changes
once I can actually test this I'll do a final review

2022-12-13 00:12 UTC, TopiSenpai commented on discord/application_role_connection_metadata.go
> +	IntegerLessThanOrEqual ApplicationRoleConnectionMetadataType = iota + 1
for consistency sake you should prefix them with `ApplicationRoleConnectionMetadataType`. Great long consts 💀

2022-12-13 00:12 UTC, TopiSenpai commented on rest/applications.go
> +	GetApplicationRoleConnectionMetadataRecords(applicationID snowflake.ID, opts ...RequestOpt) ([]discord.ApplicationRoleConnectionMetadata, error)
I think we can omit `Records` for these endpoints, idk why discord names them like this

2022-12-14 17:42 UTC, TopiSenpai approved these changes

2022-12-14 22:52 UTC, caneleex commented
this is missing the `description` field for roles.

2022-12-15 19:17 UTC, merged